### ISSUE TITLE
可以去 https://virusshare.com 弄点样本

### ISSUE THREAD

**Issue by cryzlasm** [a232319779/mmdt#1]
可以去 https://virusshare.com 弄点样本 然后根据各路报告对应的 HASH 来训练

**Comment by a232319779** [comment]
感谢，但是没找到注册下载的地方。

**Comment by cryzlasm** [comment]
![image](https://user-images.githubusercontent.com/20424580/69247268-1ec71000-0be5-11ea-9947-1ff4470511ba.png)

https://virusshare.com/about.4n6 

https://twitter.com/VXShare
